server:
  port: 8088
  servlet:
    context-path: /auto

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/auto?currentSchema=auto"
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  type-aliases-package: com.auto.demo.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  identity: POSTGRESQSL
  not-empty: true
  mappers: com.auto.demo.base.BaseMapper
logging:
  level:
    com.auto.demo.mapper: debug
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
